import type { LucideIcon } from 'lucide-react';
import {
  // Fleet & movement
  Truck, Car, Bus, Caravan, Route, MapPin, MapPinned, Map, Signpost,
  Warehouse, TrafficCone, Plane, Ship,
  // Condition & service
  Fuel, Gauge, BatteryCharging, Disc, Wrench, Hammer, Settings, Cog,
  Droplet, Flame, Thermometer, Snowflake, CloudSnow, Sun, Power, Timer,
  // Priority & state
  TriangleAlert, CircleAlert, OctagonAlert, CircleCheck, CircleX, Ban,
  ShieldCheck, ShieldAlert, Siren, Lock, KeyRound, Info, Zap, Hourglass,
  // Marking / triage
  Flag, Star, Heart, Bookmark, Tag, CircleDot, Target, Bell, Eye,
  Award, Trophy, BadgeCheck, ThumbsUp, Pencil,
  // Work & documents
  ClipboardList, ClipboardCheck, ListChecks, FileText, Files, FileClock,
  FileSpreadsheet, Folder, Receipt, Signature, Printer, Send,
  Package, Box, Archive, Inbox,
  // People & places
  Users, User, UserPlus, Contact, HardHat, IdCard, Briefcase, Handshake,
  Building2,
  // Money & time
  DollarSign, Wallet, CreditCard, Coins, Calculator, Percent,
  Clock, AlarmClock, Calendar, CalendarCheck, History,
  // Analytics & media
  Activity, TrendingUp, TrendingDown, ChartColumn, ChartLine, ChartPie,
  Camera, Video, Wifi,
} from 'lucide-react';

/**
 * Curated leading-icon set for personal saved tabs — an on-brand lucide
 * subset (NOT emoji, per the dashboard icon rule).  Stored on a SavedTab
 * as its key (``icon``); the tab strip looks the component up here.
 *
 * lucide ships ~1,700 icons.  This stays a STATIC curated subset on
 * purpose: every icon is tree-shaken into the main bundle (~10-15 KB gzip
 * for the whole set), so the picker renders instantly with no per-icon
 * chunk requests and no load flicker.  The dialog's search box makes 100
 * feel unlimited.  (The alternative — ``lucide-react/dynamic`` over all
 * 1,700 — emits ~1,900 chunk files and fetches each icon on render; only
 * worth it if searches start coming up genuinely empty.)
 *
 * Keys are STABLE — renaming one orphans that tab's icon (the stored
 * value would stop resolving).  ADDING entries is always safe.  Order
 * below is the picker's display order, grouped by theme.
 */
export const TAB_ICONS: Record<string, LucideIcon> = {
  // ── Fleet & movement ──
  truck: Truck,
  car: Car,
  bus: Bus,
  trailer: Caravan,
  route: Route,
  pin: MapPin,
  location: MapPinned,
  map: Map,
  signpost: Signpost,
  warehouse: Warehouse,
  cone: TrafficCone,
  plane: Plane,
  ship: Ship,
  // ── Condition & service ──
  fuel: Fuel,
  gauge: Gauge,
  battery: BatteryCharging,
  tire: Disc,
  wrench: Wrench,
  hammer: Hammer,
  settings: Settings,
  cog: Cog,
  oil: Droplet,
  heat: Flame,
  temperature: Thermometer,
  cold: Snowflake,
  snow: CloudSnow,
  sun: Sun,
  power: Power,
  timer: Timer,
  // ── Priority & state ──
  alert: TriangleAlert,
  urgent: CircleAlert,
  critical: OctagonAlert,
  check: CircleCheck,
  failed: CircleX,
  blocked: Ban,
  shield: ShieldCheck,
  risk: ShieldAlert,
  siren: Siren,
  lock: Lock,
  key: KeyRound,
  info: Info,
  zap: Zap,
  waiting: Hourglass,
  // ── Marking / triage ──
  flag: Flag,
  star: Star,
  heart: Heart,
  bookmark: Bookmark,
  tag: Tag,
  dot: CircleDot,
  target: Target,
  bell: Bell,
  watch: Eye,
  award: Award,
  trophy: Trophy,
  verified: BadgeCheck,
  thumbsup: ThumbsUp,
  pencil: Pencil,
  // ── Work & documents ──
  clipboard: ClipboardList,
  inspected: ClipboardCheck,
  checklist: ListChecks,
  file: FileText,
  files: Files,
  pending: FileClock,
  spreadsheet: FileSpreadsheet,
  folder: Folder,
  receipt: Receipt,
  signature: Signature,
  printer: Printer,
  send: Send,
  package: Package,
  box: Box,
  archive: Archive,
  inbox: Inbox,
  // ── People & places ──
  users: Users,
  user: User,
  invite: UserPlus,
  contact: Contact,
  crew: HardHat,
  badge: IdCard,
  briefcase: Briefcase,
  handshake: Handshake,
  building: Building2,
  // ── Money & time ──
  dollar: DollarSign,
  wallet: Wallet,
  card: CreditCard,
  coins: Coins,
  calculator: Calculator,
  percent: Percent,
  clock: Clock,
  alarm: AlarmClock,
  calendar: Calendar,
  scheduled: CalendarCheck,
  history: History,
  // ── Analytics & media ──
  activity: Activity,
  trend: TrendingUp,
  declining: TrendingDown,
  bars: ChartColumn,
  line: ChartLine,
  pie: ChartPie,
  camera: Camera,
  video: Video,
  wifi: Wifi,
};

/** Ordered keys for the picker (insertion order above = display order). */
export const TAB_ICON_KEYS = Object.keys(TAB_ICONS);

/**
 * Extra search terms per icon — so the picker finds an icon by what a
 * user CALLS it, not just by our key ("gas" → fuel, "wheel" → tire,
 * "reefer" → cold).  Keys without an entry are searched by key name
 * alone.  Terms are lower-case, space-separated.
 */
export const TAB_ICON_TERMS: Record<string, string> = {
  truck: 'vehicle lorry semi tractor rig',
  car: 'vehicle auto',
  bus: 'vehicle coach',
  trailer: 'caravan van dry reefer',
  route: 'trip lane path directions',
  pin: 'place location marker map',
  location: 'place address geofence',
  map: 'atlas area region',
  signpost: 'direction sign junction',
  warehouse: 'depot yard terminal dock',
  cone: 'roadside construction hazard work zone',
  plane: 'air freight flight',
  ship: 'sea ocean freight port',
  fuel: 'gas diesel pump fill def',
  gauge: 'meter dial reading level',
  battery: 'charge power electric volt',
  tire: 'wheel tyre rubber brake disc',
  wrench: 'repair service maintenance fix shop',
  hammer: 'repair build fix',
  settings: 'config gear preferences options',
  cog: 'gear mechanical config',
  oil: 'fluid drop lube coolant leak',
  heat: 'fire hot burn engine overheat',
  temperature: 'temp thermometer degrees climate',
  cold: 'freeze frozen winter ice reefer snow',
  snow: 'winter storm weather ice',
  sun: 'weather clear summer day',
  power: 'on off electric shutdown',
  timer: 'countdown duration stopwatch',
  alert: 'warning caution triangle attention',
  urgent: 'warning important attention priority',
  critical: 'severe emergency stop danger',
  check: 'done complete ok pass approved success',
  failed: 'fail error rejected no cross',
  blocked: 'ban denied forbidden stop void',
  shield: 'safe secure protected compliance',
  risk: 'unsafe insecure violation compliance warning',
  siren: 'emergency incident crash alarm',
  lock: 'secure locked private closed',
  key: 'access credential permission unlock',
  info: 'information note detail about',
  zap: 'fast electric quick instant power',
  waiting: 'pending queue hourglass delay',
  flag: 'mark flagged review important',
  star: 'favorite favourite important top',
  heart: 'favorite liked saved',
  bookmark: 'saved marked later',
  tag: 'label category chip',
  dot: 'circle marker point simple',
  target: 'goal objective aim focus kpi',
  bell: 'notification alert reminder',
  watch: 'eye monitor observe watchlist review',
  award: 'prize recognition best',
  trophy: 'win best top performer',
  verified: 'approved confirmed certified valid',
  thumbsup: 'good approve like ok',
  pencil: 'edit draft write note',
  clipboard: 'task list work order job',
  inspected: 'inspection dvir passed audit',
  checklist: 'tasks todo steps items',
  file: 'document doc paper record',
  files: 'documents batch multiple records',
  pending: 'awaiting overdue due document clock',
  spreadsheet: 'excel csv sheet export data',
  folder: 'group directory collection',
  receipt: 'invoice bill payment expense',
  signature: 'signed sign approval authorize',
  printer: 'print paper output',
  send: 'submit dispatch share deliver',
  package: 'parcel shipment cargo freight',
  box: 'container inventory item stock',
  archive: 'archived stored old closed',
  inbox: 'incoming queue new received',
  users: 'team people staff group drivers',
  user: 'person driver individual member',
  invite: 'add person new hire onboard',
  contact: 'phone person details card',
  crew: 'worker driver mechanic helmet staff',
  badge: 'id license cdl credential card',
  briefcase: 'business work job company',
  handshake: 'deal partner customer broker agreement',
  building: 'office company facility site',
  dollar: 'money cost price usd cash amount',
  wallet: 'money balance funds account',
  card: 'credit payment fuel card charge',
  coins: 'money cash change small',
  calculator: 'math total compute sum',
  percent: 'rate margin ratio discount',
  clock: 'time hours duration',
  alarm: 'reminder wake due alert time',
  calendar: 'date schedule month day',
  scheduled: 'planned booked date confirmed',
  history: 'past log previous audit trail',
  activity: 'pulse live status health',
  trend: 'up growth increase rising improve',
  declining: 'down decrease falling worse loss',
  bars: 'chart bar graph stats report column',
  line: 'chart graph trend stats',
  pie: 'chart share split distribution',
  camera: 'dashcam photo image capture',
  video: 'footage clip recording playback',
  wifi: 'signal connected online network telematics',
};
