/**
 * Phosphor under our names. GENERATED SHAPE — the mapping is by hand
 * (Phosphor's vocabulary is its own: `ArrowsLeftRight` for
 * `ArrowRightLeft`, `Warning` for `AlertTriangle`), and every target
 * was checked to exist against the installed package rather than
 * guessed. Two are approximations and say so: parking has no Phosphor
 * glyph and takes a car; `FileClock` has no timed-file glyph and takes
 * a plain file.
 *
 * 256 names — the same 256 `names.ts` declares, which is what
 * `iconLane.test.ts` checks.
 */
export {
  ActivityIcon as Activity,
  Alarm as AlarmClock,
  WarningCircle as AlertCircle,
  Warning as AlertTriangle,
  Archive,
  BoxArrowUp as ArchiveRestore,
  ArrowDown,
  ArrowLeft,
  ArrowLineLeft as ArrowLeftToLine,
  ArrowRight,
  ArrowsLeftRight as ArrowRightLeft,
  ArrowLineRight as ArrowRightToLine,
  ArrowUp,
  ArrowCircleUp as ArrowUpCircle,
  ArrowsDownUp as ArrowUpDown,
  ArrowUpRight,
  Medal as Award,
  SealCheck as BadgeCheck,
  CurrencyCircleDollar as BadgeDollarSign,
  Prohibit as Ban,
  ChartBar as BarChart3,
  BatteryCharging,
  Bed as BedDouble,
  Bell,
  BellSlash as BellOff,
  BellRinging as BellRing,
  BookOpen,
  Bookmark,
  Robot as Bot,
  Cube as Box,
  Cube as Boxes,
  Brain,
  Briefcase,
  Buildings as Building2,
  Bus,
  Calculator,
  Calendar,
  CalendarCheck,
  CalendarDots as CalendarDays,
  CalendarBlank as CalendarRange,
  Camera,
  Car,
  Van as Caravan,
  ChartBar as ChartColumn,
  ChartLine,
  ChartPie,
  Check,
  Checks as CheckCheck,
  CheckCircle as CheckCircle2,
  CheckSquare,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  CaretDoubleDown as ChevronsDown,
  ArrowsInLineVertical as ChevronsDownUp,
  CaretDoubleUp as ChevronsUp,
  CaretUpDown as ChevronsUpDown,
  Circle,
  WarningCircle as CircleAlert,
  CheckCircle as CircleCheck,
  CircleDashed,
  RadioButton as CircleDot,
  CarSimple as CircleParking,
  Prohibit as CircleSlash,
  XCircle as CircleX,
  ClipboardText as ClipboardCheck,
  ClipboardText as ClipboardList,
  Clock,
  Clock as Clock3,
  Cloud,
  CloudSlash as CloudOff,
  CloudSnow,
  Gear as Cog,
  Coins,
  Columns as Columns3,
  AddressBook as Contact,
  Copy,
  ArrowElbowUpRight as CornerUpRight,
  CreditCard,
  Crown,
  Database,
  Disc,
  CurrencyDollar as DollarSign,
  Download,
  Drop as Droplet,
  DropHalf as Droplets,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileText as FileClock,
  FileArrowDown as FileDown,
  FileImage,
  FileXls as FileSpreadsheet,
  FileText,
  FileVideo,
  Files,
  Funnel as Filter,
  Flag,
  Flame,
  Flask as FlaskConical,
  Folder,
  FolderOpen,
  GasPump as Fuel,
  Gauge,
  Gift,
  Globe,
  GraduationCap,
  DotsSixVertical as GripVertical,
  Stack as Group,
  Hammer,
  Handshake,
  HardDrive,
  HardHat,
  Heart,
  Heartbeat as HeartPulse,
  Question as HelpCircle,
  ClockCounterClockwise as History,
  House as Home,
  Hourglass,
  IdentificationCard as IdCard,
  Image,
  ImageSquare as ImagePlus,
  Tray as Inbox,
  Info,
  Key as KeyRound,
  Bank as Landmark,
  Stack as Layers,
  SquaresFour as LayoutDashboard,
  SquaresFour as LayoutGrid,
  Lightbulb,
  Link,
  Link as Link2,
  LinkBreak as Link2Off,
  List,
  ListChecks,
  TreeStructure as ListTree,
  CircleNotch as Loader2,
  Lock,
  SignOut as LogOut,
  Envelope as Mail,
  MapTrifold as Map,
  MapPin,
  MapPinLine as MapPinned,
  ArrowsOut as Maximize2,
  List as Menu,
  ArrowsMerge as Merge,
  ChatCircle as MessageCircle,
  Chat as MessageSquare,
  Microscope,
  ArrowsIn as Minimize2,
  Minus,
  Monitor,
  Devices as MonitorSmartphone,
  DotsThreeVertical as MoreVertical,
  Mountains as Mountain,
  ArrowsHorizontal as MoveHorizontal,
  WarningOctagon as OctagonAlert,
  XCircle as OctagonX,
  Package,
  Package as PackageX,
  Palette,
  SidebarSimple as PanelLeftClose,
  Sidebar as PanelLeftOpen,
  SquareHalf as PanelTopClose,
  Paperclip,
  CarSimple as ParkingCircle,
  CarSimple as ParkingSquare,
  PencilSimpleLine as PenLine,
  Pencil,
  Percent,
  PushPin as Pin,
  PushPinSlash as PinOff,
  Airplane as Plane,
  Play,
  Plug,
  Plus,
  Power,
  Printer,
  PuzzlePiece as Puzzle,
  Broadcast as RadioTower,
  Receipt,
  ArrowsCounterClockwise as RefreshCcw,
  ArrowsClockwise as RefreshCw,
  ArrowCounterClockwise as RotateCcw,
  ArrowClockwise as RotateCw,
  Path as Route,
  Rows as Rows2,
  Rows as Rows3,
  Rows as Rows4,
  Broadcast as Satellite,
  FloppyDisk as Save,
  Scales as Scale,
  Scroll as ScrollText,
  MagnifyingGlass as Search,
  PaperPlaneTilt as Send,
  HardDrives as Server,
  Gear as Settings,
  GearSix as Settings2,
  Shield,
  ShieldWarning as ShieldAlert,
  ShieldCheck,
  Boat as Ship,
  Shower as ShowerHead,
  Sigma,
  Signature,
  Signpost,
  Siren,
  SlidersHorizontal,
  DeviceMobile as Smartphone,
  Snowflake,
  Sparkle as Sparkles,
  Square,
  CarSimple as SquareParking,
  NotePencil as SquarePen,
  Star,
  Note as StickyNote,
  Storefront as Store,
  Sun,
  Table as Table2,
  Table as TableProperties,
  DeviceTablet as Tablet,
  Tag,
  Target,
  Thermometer,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Timer as TimerReset,
  TrafficCone,
  Trash as Trash2,
  TrendDown as TrendingDown,
  TrendUp as TrendingUp,
  Warning as TriangleAlert,
  Trophy,
  Truck,
  ArrowUUpLeft as Undo2,
  Selection as Ungroup,
  LinkBreak as Unlink,
  Upload,
  CloudArrowUp as UploadCloud,
  User,
  UserGear as UserCog,
  UserPlus,
  Users,
  Video,
  SpeakerHigh as Volume2,
  SpeakerX as VolumeX,
  Wallet,
  MagicWand as Wand2,
  Warehouse,
  WifiHigh as Wifi,
  Wrench,
  X,
  XCircle,
  Lightning as Zap,
} from '@phosphor-icons/react';
