"""Generate every client's provider artwork from the canonical assets.

A provider's mark is ONE file — ``capabilities/integrations/<provider>/
assets/logo.svg`` — and every client draws it inline, because each path
is ``currentColor``: an image element renders in its own document, where
that resolves to black, so one inlined file is what covers the light
theme, the dark theme and any accent the Colour picker lands on.

"Inline" means each client needs the paths in ITS OWN source tree; the
browser extension is a separate Vite app and cannot import from the
dashboard, let alone from the Python package that owns the asset. That
is a copy, and a copy made by hand is a copy that drifts — so it is made
here instead, and each app's test re-derives from the asset and fails if
the generated file was edited.

    python3 scripts/gen_provider_marks.py            # write
    python3 scripts/gen_provider_marks.py --check    # CI: fail on drift

Adding a provider: drop its logo.svg beside its integration and add one
line to TARGETS' component list below — the kind (wordmark vs glyph)
lives with each client's registry, because it is a rendering decision.
"""
from __future__ import annotations

import argparse
import pathlib
import sys
import xml.etree.ElementTree as ET

SVG_NS = "{http://www.w3.org/2000/svg}"
REPO = pathlib.Path(__file__).resolve().parent.parent
ASSETS = REPO / "capabilities" / "integrations"

#: Every client that draws provider marks, and where its file goes.
TARGETS = [
    REPO / "interfaces/dashboard/src/features/vehicles/providerMarks.tsx",
    REPO / "interfaces/browser_extension/src/features/live-map/providerMarks.tsx",
]

#: provider -> the component name clients import.
PROVIDERS = {"samsara": "SamsaraWordmark"}

HEADER = '''/**
 * Provider artwork — GENERATED by scripts/gen_provider_marks.py from
 * capabilities/integrations/<provider>/assets/logo.svg.  Do not edit:
 * the generator is the only writer, and this app's test re-derives from
 * the asset and fails on drift.
 *
 * Inlined as SVG, never an image element: every path takes its colour
 * from the text around it, and an image renders in its own document
 * where that resolves to black.  Inline means ONE asset serves the
 * light theme, the dark theme and any accent.
 */
'''


def component(name: str, view_box: str, label: str, paths: list[str]) -> str:
    body = "\n".join(f'      <path d="{d}" fill="currentColor" />' for d in paths)
    return f'''
/** {label}'s wordmark.  Height-driven — the width follows its box. */
export function {name}({{ className = '' }}: {{ className?: string }}) {{
  return (
    <svg viewBox="{view_box}" role="img" aria-label="{label}" fill="none"
         xmlns="http://www.w3.org/2000/svg"
         className={{`w-auto ${{className}}`}}>
{body}
    </svg>
  );
}}
'''


def render() -> str:
    out = [HEADER]
    for provider, name in sorted(PROVIDERS.items()):
        svg = ASSETS / provider / "assets" / "logo.svg"
        if not svg.is_file():
            raise SystemExit(f"missing asset: {svg.relative_to(REPO)}")
        root = ET.parse(svg).getroot()
        paths = [p.get("d") for p in root.iter(f"{SVG_NS}path")]
        if not paths:
            raise SystemExit(f"no paths in {svg.relative_to(REPO)}")
        out.append(component(name, root.get("viewBox", ""),
                             provider.capitalize(), paths))
    return "".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any target is missing or stale")
    args = ap.parse_args()
    want = render()
    stale = [t for t in TARGETS
             if not t.is_file() or t.read_text() != want]
    if args.check:
        for t in stale:
            print(f"stale or missing: {t.relative_to(REPO)}", file=sys.stderr)
        if stale:
            print("run: python3 scripts/gen_provider_marks.py", file=sys.stderr)
        return 1 if stale else 0
    for t in TARGETS:
        t.parent.mkdir(parents=True, exist_ok=True)
        t.write_text(want)
        print(f"wrote {t.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
